# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: GitHub Smart Chips
site_url: https://ianlewis.github.io/github-smart-chips/
repo_url: https://github.com/ianlewis/github-smart-chips
docs_dir: web
site_dir: _site

theme:
  name: landing
  favicon: github-mark-white.png

  header_layout:
    - avatar
    - title
    - tagline
    - socials
  avatar: GitHub-Mark.png
  avatar_size: 15rem
  tagline: "Smart Chip Preview Links for Google Workspace."

  page_source:
    link: https://github.com/ianlewis/github-smart-chips

  socials:
    - label: GitHub
      link: https://github.com/ianlewis/github-smart-chips
      icon: [brands, github]

  heading_font: Poppins
  heading_font_files:
    regular: "fonts/Poppins-Regular.ttf"
    bold: "fonts/Poppins-Bold.ttf"
    italic: "fonts/Poppins-Italic.ttf"
    bold_italic: "fonts/Poppins-BoldItalic.ttf"
  # body font
  body_font: Noto Sans
  body_font_files:
    regular: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    bold: "fonts/NotoSans-VariableFont_wdth,wght.ttf"
    italic: "fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf"
    bold_italic: "fonts/NotoSans-Italic-VariableFont_wdth,wght.ttf"
  # monospace font
  mono_font: JetBrains Mono
  mono_font_files:
    regular: "fonts/JetBrainsMono-VariableFont_wght.ttf"
    bold: "fonts/JetBrainsMono-VariableFont_wght.ttf"
    italic: "fonts/JetBrainsMono-Italic-VariableFont_wght.ttf"
    bold_italic: "fonts/JetBrainsMono-Italic-VariableFont_wght.ttf"

  share_btn: false
